theme: minima
title: Pagina Web Francisco Meza
author: Franjmc13
email: L161061083@mulege.tecnm.mx
description: > # this means to ignore newlines until "baseurl:"
  El Asombroso Blog de Francisco Javier Meza Camacho

# social links
github_username: Franjmc13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
